### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by yamatazen** [spacepxl/ComfyUI-Florence-2#15]
This is the error message on the console.
\Traceback (most recent call last):
  File "C:\Users\yamat\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\yamat\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence-2\__init__.py", line 1, in <module>
    from .Florence import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Users\yamat\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence-2\Florence.py", line 9, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'

Cannot import C:\Users\yamat\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence-2 module for custom nodes: No module named 'matplotlib'

**Comment by jfjensen** [comment]
same issue here
