### ISSUE TITLE
[Error]: list.remove(x): x not in list

### ISSUE THREAD

**Issue by nhathoangfoto** [spacepxl/ComfyUI-Florence-2#19]
<img width="1370" alt="image" src="https://github.com/user-attachments/assets/d68af9d3-0a2e-40c3-931d-622571b6763c">
I was using it normally until today when I ran my workflow to the Florence2 model loading node and got this error, even though I haven't deleted any models.

**Comment by Twelve615** [comment]
I'm having this problem too, I'm using linux
![image](https://github.com/user-attachments/assets/fb026772-1bd7-4d06-b5e6-2501cb8a07a3)

The logs are as follows：
```log
got prompt
A new version of the following files was downloaded from https://huggingface.co/microsoft/Florence-2-large-ft:
- configuration_florence2.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
!!! Exception during processing !!! list.remove(x): x not in list
Traceback (most recent call last):
  File "/home/featurize/work/app/comfyui/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/featurize/work/app/comfyui/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/featurize/work/app/comfyui/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/featurize/work/app/comfyui/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/featurize/work/app/comfyui/ComfyUI/custom_nodes/ComfyUI-Florence-2/Florence.py", line 149, in load
    self.model, self.processor = load_model(version, self.device)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/featurize/work/app/comfyui/ComfyUI/custom_nodes/ComfyUI-Florence-2/Florence.py", line 41, in load_model
    model = AutoModelForCausalLM.from_pretrained(identifier, cache_dir=comfy_model_dir, trust_remote_code=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/featurize/work/app/comfyui/env/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 553, in from_pretrained
    model_class = get_class_from_dynamic_module(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/featurize/work/app/comfyui/env/lib/python3.11/site-packages/transformers/dynamic_module_utils.py", line 540, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/featurize/work/app/comfyui/env/lib/python3.11/site-packages/transformers/dynamic_module_utils.py", line 365, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/featurize/work/app/comfyui/env/lib/python3.11/site-packages/transformers/dynamic_module_utils.py", line 181, in check_imports
    imports = get_imports(filename)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/featurize/work/app/comfyui/ComfyUI/custom_nodes/ComfyUI-Florence-2/Florence.py", line 29, in fixed_get_imports
    imports.remove("flash_attn")
ValueError: list.remove(x): x not in list
```
Then I noticed that the folder in the image below was created after execution
![image](https://github.com/user-attachments/assets/3d4225f0-378c-4feb-a5e4-b98f760a3427)
I noticed this message in the beginning of the logs：
```
A new version of the following files was downloaded from https://huggingface.co/microsoft/Florence-2-large-ft:
- configuration_florence2.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
```
In the folder created by the node there is the file `configuration_florence2.py`
![image](https://github.com/user-attachments/assets/b43ed208-3730-4a91-8f3c-7b3f488f1f87)

Only the path is in: `/home/featurize/work/app/comfyui/ComfyUI/models/LLM/models--microsoft--Florence-2-large-ft/snapshots/bb44b80c15e943b1bf7cec6e076359cec6e40178` Under this folder

I looked again at the contents of your source code `Florence.py` and on line 37 of the file in the `load_model` function it says `identifier = "microsoft/Florence-2-" + version` so I assumed that the path might be `ComfyUI/models/LLM/ microsoft/Florence-2-large-ft` so I moved the contents in there and still have the problem.

Now I noticed that there are many exceptions thrown by `transformers` in the logs, I would like to try the following to change the version of my `transformers`, my version is `transformers-4.45.0` but you don't have `requirements.txt` written in your project so can you please tell me the version that you are using? , please.

**Comment by Twelve615** [comment]
**By the way, my environmental information is here.**
## System Information
- **ComfyUI Version:** v0.2.2-33-gf6b7194
- **Arguments:** main.py --listen 0.0.0.0 --port 23810
- **OS:** posix
- **Python Version:** 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0]
- **Embedded Python:** false
- **PyTorch Version:** 2.4.1+cu121

**Comment by XyW-Max** [comment]
same issue

**Comment by ql0wn4** [comment]
It seems like nobody cares... am I wrong?

**Comment by diripirate** [comment]
It happened to me. I found a workaround, it probably causes some error at some point, but til now is working for me.

Goto the Florence.py file, line 29 and comment it:
`29> # imports.remove("flash_attn")`
